from __future__ import annotations

import hashlib
from datetime import datetime, timezone
from typing import Any, Dict, List

from .models import Finding, PolicyEvaluationRequest


def _hash_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _render_change_log(request: PolicyEvaluationRequest, findings: List[Finding], health: Dict[str, Any]) -> str:
    lines = [
        f"# PR {request.pr_number} Knowledge Update",
        "",
        f"Repository: {request.repo}",
        f"Generated: {datetime.now(timezone.utc).isoformat()}",
        "",
        "## Health Snapshot",
        f"- Score: {health.get('score')}",
        f"- Grade: {health.get('grade')}",
        "",
        "## Findings",
    ]
    if not findings:
        lines.append("- No findings")
    for f in findings:
        lines.append(f"- [{f.rule_id}] {f.title}: {f.description}")
    return "\n".join(lines)


def _render_adr(request: PolicyEvaluationRequest, findings: List[Finding], merge_gate: Dict[str, Any]) -> str:
    lines = [
        "# ADR: PR Policy Governance Decision",
        "",
        f"- Repo: {request.repo}",
        f"- PR: {request.pr_number}",
        f"- Generated: {datetime.now(timezone.utc).isoformat()}",
        "",
        "## Context",
        f"Policy findings count: {len(findings)}",
        "",
        "## Decision",
        f"Merge gate decision: {merge_gate.get('decision')}",
        "",
        "## Evidence",
    ]
    for f in findings[:10]:
        lines.append(f"- {f.rule_id}: {f.title}")
    lines.extend(["", "## Consequences", "- This ADR was auto-generated and should be reviewed by maintainers."])
    return "\n".join(lines)


def build_doc_rewrite_bundle(
    *,
    request: PolicyEvaluationRequest,
    findings: List[Finding],
    doc_refresh_plan: Dict[str, Any],
    merge_gate: Dict[str, Any],
    knowledge_health: Dict[str, Any],
) -> Dict[str, Any]:
    change_doc = _render_change_log(request, findings, knowledge_health)
    adr_doc = _render_adr(request, findings, merge_gate)

    prn = request.pr_number or 0
    targets = [
        {
            "file_path": f"docs/changes/pr-{prn}-knowledge-update.md",
            "template": "change-log",
            "content": change_doc,
            "content_hash": _hash_text(change_doc),
        },
        {
            "file_path": f"docs/adr/ADR-pr-{prn}-policy-governance.md",
            "template": "adr",
            "content": adr_doc,
            "content_hash": _hash_text(adr_doc),
        },
    ]

    source_targets = doc_refresh_plan.get("target_files") or []
    for idx, tf in enumerate(source_targets):
        scaffold = "\n".join(
            [
                f"# Autogenerated Update Scaffold ({idx + 1})",
                "",
                f"Target: {tf}",
                f"Repo: {request.repo}",
                f"PR: {request.pr_number}",
                "",
                "## Required updates",
                "- Align documentation with detected API/schema changes.",
                "- Add owner metadata and migration notes.",
            ]
        )
        targets.append(
            {
                "file_path": tf,
                "template": "propagated-scaffold",
                "content": scaffold,
                "content_hash": _hash_text(scaffold),
            }
        )

    return {
        "repo": request.repo,
        "pr_number": request.pr_number,
        "decision": doc_refresh_plan.get("decision"),
        "priority": doc_refresh_plan.get("priority"),
        "targets": targets,
        "generated_at": datetime.now(timezone.utc).isoformat(),
    }
