from __future__ import annotations

from typing import List

from .models import Citation, Finding, SuggestedPatch


def _doc_stub_diff(doc_path: str, heading: str, body: str) -> str:
    return "\n".join(
        [
            f"--- a/{doc_path}",
            f"+++ b/{doc_path}",
            "@@ -0,0 +1,8 @@",
            f"+# {heading}",
            "+",
            f"+{body}",
            "+",
            "+## Owner",
            "+- TODO: set service/endpoint owner",
            "+",
        ]
    )


def _owner_config_diff(path: str, key: str) -> str:
    return "\n".join(
        [
            f"--- a/{path}",
            f"+++ b/{path}",
            "@@ -1,3 +1,4 @@",
            " owners:",
            f"+  {key}: team-example-owner",
            "",
        ]
    )


def build_suggested_patches(findings: List[Finding]) -> List[SuggestedPatch]:
    patches: List[SuggestedPatch] = []

    doc_related = [f for f in findings if f.rule_id == "DOC_DRIFT_ENDPOINT_CHANGED_NO_DOC"]
    if doc_related:
        patches.append(
            SuggestedPatch(
                patch_id="patch-doc-stub-001",
                patch_type="doc_stub",
                file_path="docs/changes/pr-notes.md",
                summary="Add PR-facing API change documentation stub with owner placeholder",
                unified_diff=_doc_stub_diff(
                    "docs/changes/pr-notes.md",
                    "API Drift Notes",
                    "Autogenerated stub: document endpoint changes and migration guidance.",
                ),
                citations=[
                    Citation(kind="spec", reference="head_spec.endpoints", details="Missing doc update for endpoint change")
                ],
            )
        )

    owner_related = [f for f in findings if f.rule_id == "DOC_DRIFT_MISSING_OWNER"]
    if owner_related:
        patches.append(
            SuggestedPatch(
                patch_id="patch-owner-map-001",
                patch_type="config_tweak",
                file_path="config/owners.yml",
                summary="Add missing owner mapping entries for changed endpoints",
                unified_diff=_owner_config_diff("config/owners.yml", "service.endpoint"),
                citations=[Citation(kind="entity", reference="owner-metadata", details="Missing owner metadata")],
            )
        )

    return patches
