# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import services_pb2 as services__pb2


class GraphServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ApplyMutations = channel.unary_unary(
                '/kabrain.GraphService/ApplyMutations',
                request_serializer=services__pb2.ApplyMutationsRequest.SerializeToString,
                response_deserializer=services__pb2.ApplyMutationsResponse.FromString,
                )


class GraphServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ApplyMutations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GraphServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ApplyMutations': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplyMutations,
                    request_deserializer=services__pb2.ApplyMutationsRequest.FromString,
                    response_serializer=services__pb2.ApplyMutationsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kabrain.GraphService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GraphService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ApplyMutations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kabrain.GraphService/ApplyMutations',
            services__pb2.ApplyMutationsRequest.SerializeToString,
            services__pb2.ApplyMutationsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class HealthServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Check = channel.unary_unary(
                '/kabrain.HealthService/Check',
                request_serializer=services__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=services__pb2.HealthCheckResponse.FromString,
                )


class HealthServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Check(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HealthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Check': grpc.unary_unary_rpc_method_handler(
                    servicer.Check,
                    request_deserializer=services__pb2.HealthCheckRequest.FromString,
                    response_serializer=services__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kabrain.HealthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class HealthService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Check(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kabrain.HealthService/Check',
            services__pb2.HealthCheckRequest.SerializeToString,
            services__pb2.HealthCheckResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class AnalysisServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EnqueueJob = channel.unary_unary(
                '/kabrain.AnalysisService/EnqueueJob',
                request_serializer=services__pb2.EnqueueJobRequest.SerializeToString,
                response_deserializer=services__pb2.EnqueueJobResponse.FromString,
                )


class AnalysisServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def EnqueueJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnalysisServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EnqueueJob': grpc.unary_unary_rpc_method_handler(
                    servicer.EnqueueJob,
                    request_deserializer=services__pb2.EnqueueJobRequest.FromString,
                    response_serializer=services__pb2.EnqueueJobResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kabrain.AnalysisService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AnalysisService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def EnqueueJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kabrain.AnalysisService/EnqueueJob',
            services__pb2.EnqueueJobRequest.SerializeToString,
            services__pb2.EnqueueJobResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class AgentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitAgentTask = channel.unary_unary(
                '/kabrain.AgentService/SubmitAgentTask',
                request_serializer=services__pb2.SubmitAgentTaskRequest.SerializeToString,
                response_deserializer=services__pb2.SubmitAgentTaskResponse.FromString,
                )


class AgentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubmitAgentTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitAgentTask': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitAgentTask,
                    request_deserializer=services__pb2.SubmitAgentTaskRequest.FromString,
                    response_serializer=services__pb2.SubmitAgentTaskResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kabrain.AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AgentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubmitAgentTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/kabrain.AgentService/SubmitAgentTask',
            services__pb2.SubmitAgentTaskRequest.SerializeToString,
            services__pb2.SubmitAgentTaskResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
